
train_list: './dump/train.list'
outdir: './fastspeech'

batch_size: 32
eval_steps_per_batches: 10
num_epochs: 100

log_interval_steps: 300
eval_interval_steps: 500
save_interval_steps: 500

learning_rate: 0.0001
beta_1: 0.9
beta_2: 0.98
epsilon: 0.00001



model_name: 'FastSpeech'
n_speakers: 10
hidden_size: 384
num_hidden_layers: 6
num_attention_heads: 2
intermediate_size: 512
intermediate_kernel_size: 3
num_duration_conv_layers: 2
duration_predictor_filters: 256
duration_predictor_kernel_sizes: 3
hidden_act: "mish"
hidden_dropout_prob: 0.0
attention_probs_dropout_prob: 0.0
duration_predictor_dropout_probs: 0.0
max_position_embeddings: 2048
initializer_range: 0.02
layer_norm_eps: 0.00001
output_attentions: False
output_hidden_states: True
n_conv_postnet: 5
postnet_conv_filters: 256
postnet_conv_kernel_sizes: 3
postnet_dropout_rate: 0.0